// get a list of all product
GET http://localhost:3000/products

### crate a product

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Apple Watch",
    "price": 8888
}

### get a product by id
# GET   http://localhost:3000/products/id
GET   http://localhost:3000/products/6419186f22292fb40175c14d

### update a product by id
PATCH   http://localhost:3000/products/6419186f22292fb40175c14d
Content-Type: application/json

{
  "price": 3453453453
}

### delete a product by id
DELETE   http://localhost:3000/products/641a6a31c1d41455549c07ea

### 404 not found
GET http://localhost:3000/abc_xyz

###
GET  http://localhost:3000/test?name=iMac&price=2399

###
GET  http://localhost:3000/test/365469432121/iMac

###

POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

name=iMac&price=499
 
